### PR TITLE
Fixed ChildPages animation sometimes stuck when interrupted

### LINKED ISSUE #868: Race condition within ChildPages
I have nested ChildPages. e.g. first level pager: A/B/C, and B have it's own child pager (D/E/F)

When I navigate to B, the initial child page is D, then I navigate to A.

There is a button on A, when I click it, it needs to navigate to B and switch the child page to F.

The weird behavior is, when I click the button,  I call the `PagesNavigation` within first level to `select` B and call the `PagesNavigation` within B to `select` F. But the Compose side, when executing [these block](https://github.com/arkivanov/Decompose/blob/master/extensions-compose/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/pages/ChildPages.kt#L76-L82), the `currentPage` and `targetPage` stay at D, causing receiving `onPageSelected(D)` and childPages.selectedIndex is 2 (F).

Then it keeps switching between D and F without end...

Not sure how to avoid this behavior?

### PR DESCRIPTION
**Pull request by arkivanov**
Fixes #868.

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevents programmatic page scrolls from triggering while the user is actively swiping, reducing jitter and accidental jumps.
  * Ensures smoother, consistent animations for page transitions when idle.
  * Reduces chances of redundant scroll actions, improving overall paging stability.

* **Chores**
  * No public API changes.

### CODE REVIEW

File: extensions-compose/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/pages/ChildPages.kt [hunk 1]
```diff
@@ -64,7 +64,7 @@ fun <C : Any, T : Any> ChildPages(
     )
 
     LaunchedEffect(selectedIndex) {
-        if (state.currentPage != selectedIndex) {
+        if (!state.isScrollInProgress) {
```
Comment (Nek-12) [inline extensions-compose/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/pages/ChildPages.kt:67]: This will not solve the issue - it will make the situation worse.
Now the pager will miss events, leaving it in an inconsistent state, when events are rapidly issued programmatically during scroll. 

When the animation will not have enough time to catch up, it will get stale, only scrolling to whatever index it was initially trying to scroll to.

Comment (Nek-12) [reply extensions-compose/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/pages/ChildPages.kt:67]: A proper solution is to remove programmatic scroll logic (`pages.select` function) or use synchronization primitives such as queues and mutexes to ensure commands are canceled and reinvoked at appropriate times)

Comment (arkivanov) [reply extensions-compose/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/pages/ChildPages.kt:67]: I did test it thoroughly and it worked fine in all known cases.

> when events are rapidly issued programmatically during scroll

That's exactly what the slider does in the reproducer you provider. I also extensively tested it with rapid navigation commands in a loop (like calling `select(random)` with random values). Works fine now. 

> A proper solution is to remove programmatic scroll logic (`pages.select` function) 

There is no way it will be removed, sorry.

> use synchronization primitives such as queues and mutexes to ensure commands are canceled and reinvoked at appropriate times

Let's see how it works once the next `3.4.0-alpha04` version is released. If there are any issues, please file a new bug. That's exactly the purpose of alpha testing.
